code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dawhite.mustache
code --install-extension dbaeumer.vscode-eslint
code --install-extension dpkshrma.insert-iso-timestamp
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension glen-84.sass-lint
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mohsen1.prettify-json
code --install-extension ms-mssql.mssql
code --install-extension ms-vscode.sublime-keybindings
code --install-extension Orta.vscode-jest
code --install-extension ow.vscode-subword-navigation
code --install-extension patrys.vscode-code-outline
code --install-extension robinbentley.sass-indented
code --install-extension sdras.night-owl
code --install-extension tomoki1207.vscode-input-sequence
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one