export DOTFILES_PATH="$HOME/git/dotfiles/public"

# loads all the PATH variables
source $DOTFILES_PATH/env.sh

# Add deno completions to search path
if [[ ":$FPATH:" != *":/Users/danieluhl/.zsh/completions:"* ]]; then export FPATH="/Users/danieluhl/.zsh/completions:$FPATH"; fi

# first load oh-my-zsh so we can overwrite here
[[ -f ~/.ohmyzshrc ]] && source ~/.ohmyzshrc

# for ai sescrets
[[ -f ~/.config/secrets/.ai-secrets ]] && source ~/.config/secrets/.ai-secrets

# Load z
[ -f $(brew --prefix)/etc/profile.d/z.sh ] && source $(brew --prefix)/etc/profile.d/z.sh

# Load aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# Local config
# [[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
[[ -f ~/.zshrc_local ]] && source ~/.zshrc_local

# Load git completion
[[ -f ~/.git-completion.sh ]] && source ~/.git-completion.sh

autoload -Uz compinit
compinit -i

autoload -U +X bashcompinit && bashcompinit

# source $HOME/.docker/init-zsh.sh || true # Added by Docker Desktop

# disabling for faster load times
# source $DOTFILES_PATH/login.sh

# bun completions
[ -s "/Users/danieluhl/.bun/_bun" ] && source "/Users/danieluhl/.bun/_bun"

# opam configuration (OCaml)
[[ ! -r /Users/danieluhl/.opam/opam-init/init.zsh ]] || source /Users/danieluhl/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/danieluhl/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/danieluhl/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/danieluhl/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/danieluhl/google-cloud-sdk/completion.zsh.inc'; fi

# activate mise
eval "$(~/.local/bin/mise activate zsh)"
eval "$(mise activate zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


