export DOTFILES_PATH="$HOME/git/dotfiles/public"

source $DOTFILES_PATH/env.sh

# Load z
[ -f $(brew --prefix)/etc/profile.d/z.sh ] && source $(brew --prefix)/etc/profile.d/z.sh

# Load aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# Load git completion
[[ -f ~/.git-completion.sh ]] && source ~/.git-completion.sh

autoload -Uz compinit
compinit

# Activate rtx for the session (rust based pro)
eval "$(/opt/homebrew/bin/rtx activate zsh)"

autoload -U +X bashcompinit && bashcompinit

# source $HOME/.docker/init-zsh.sh || true # Added by Docker Desktop

# disabling for faster load times
# source $DOTFILES_PATH/login.sh

export STARSHIP_CONFIG="$HOME/git/dotfiles/public/config/starship.toml"
eval "$(starship init zsh)"

clear
PATH="/usr/local/bin:$PATH"

if test -f "$HOME/.zshrc_local"; then
  . "$HOME/.zshrc_local"
fi

# bun completions
[ -s "/Users/danieluhl/.bun/_bun" ] && source "/Users/danieluhl/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
