require("duhl.packer")
require("duhl.gset")
-- require("duhl.cmp")
-- require("duhl.autocmd")
-- require("duhl.null-ls")
-- require("duhl.treeshitter")
require("duhl.set")
-- require("duhl.nvim-tree")
-- require("duhl.autotag")
-- require("duhl.autocmd")
require("duhl.remap")
-- require("mason.eslint")
-- require("mason.prettier")
