require("duhl.packer")
require("duhl.gset")
require("duhl.cmp")
require("duhl.autocmd")
require("duhl.null-ls")
-- require("duhl.friendly-snippets")
require("duhl.treeshitter")
require("duhl.lspconfig")
-- require("duhl.ls-eslint")
require("duhl.ls-prettier")
require("duhl.set")
require("duhl.nvim-tree")
-- require("duhl.autotag")
-- require("duhl.autocmd")
require("duhl.remap")
